---
title: "Bottle emptying"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(knitr)
```


```{r}
data <- read.csv("combined_emptying.csv")
```


```{r}

post_threshold <- 75

data <- data %>%
  select(2:8) %>%
  # mutate(post_flag = (neonur_bot1_post < post_threshold)) %>%
  mutate(post_flag = ifelse(neonur_bot1_post < post_threshold, "Yes", "No"))

```

```{r}

table(data$Bottle.Emptying, data$post_flag, useNA = "ifany")

```


```{r}
bottle_emptying_mismatch <- data %>% filter(!(Bottle.Emptying == post_flag))
```


```{r}
bottle_emptying_mismatch %>%
  kable()

```

```{r}
write.csv(bottle_emptying_mismatch,"bottle_empyting_mismatch.csv", row.names = FALSE)
```


```{r, include = FALSE}
table(data$Dyad_set, data$timepoint)

```



```{r}

bottle_empyting_mismatch_checked <- read.csv("bottle_emptying_mismatch_checked.csv") %>%
  select(id, Dyad_set, FINAL.DECISION) %>% 
  rename(emptying = FINAL.DECISION)

```


```{r}

emptying_codes <- data %>% 
  select(1:4) %>%
  left_join(bottle_empyting_mismatch_checked,
            by = c("id" = "id", "Dyad_set" = "Dyad_set")) %>%
  mutate(emptying = ifelse(is.na(emptying), Bottle.Emptying, emptying)) %>%
  select(-Bottle.Emptying)

```


```{r}

table(emptying_codes$emptying)
```

There were 5 that were in our data and UM that did not have a post-code in UM data. (See 11/3-11/4/2021 emails)

70095 2moB No
70531 4moB No
70158 6moB No
70165 6moB No
70219 6moB Yes


We have our code but NA for UM.  Ali checked these and our code was correct, except for

70158 6moB should be Yes


```{r}
emptying_codes <- emptying_codes %>%
  mutate(emptying = replace(emptying,
                            (id == "70158") & (Dyad_set == "6moB"), "Yes"))
```

```{r}

table(emptying_codes$emptying)
```

```{r}

write.csv(emptying_codes,"emptying_codes.csv", row.names = FALSE)

```